
import { 
  LayoutDashboard, 
  Layers, 
  Image as ImageIcon, 
  Users, 
  ClipboardList, 
  FileText,
  Bell,
  Quote,
  MessageSquare,
  Settings,
  Package,
  BarChart2,
  ShoppingCart,
  Truck,
  Palette,
  Plus,
  Search,
  Database
} from 'lucide-react';

export const ADMIN_MODULES = [
  { label: 'Inventory', icon: Package, path: '/admin/inventory' },
  { label: 'SKU Lookup', icon: Search, path: '/admin/sku-lookup' },
  { label: 'Banners', icon: ImageIcon, path: '/admin/banners' },
  { label: 'Categories', icon: Layers, path: '/admin/categories' },
  { label: 'Bulk Create', icon: Plus, path: '/admin/bulk-create' },
  { label: 'Bulk Products', icon: Layers, path: '/admin/bulk-products' },
  { label: 'Manage Orders', icon: ClipboardList, path: '/admin/orders' },
  { label: 'Shipping', icon: Truck, path: '/admin/shipping' },
  { label: 'Reviews', icon: FileText, path: '/admin/reviews' },
  { label: 'Users', icon: Users, path: '/admin/users' },
  { label: 'Messages', icon: MessageSquare, path: '/admin/messages' },
  { label: 'Testimonials', icon: Quote, path: '/admin/testimonials' },
  { label: 'Announcements', icon: Bell, path: '/admin/announcements' },
  { label: 'Colors', icon: Palette, path: '/admin/colors' },
  { label: 'Settings', icon: Settings, path: '/admin/settings' },
  { label: 'Demo Data', icon: Database, path: '/admin/demo-data' },
];
